### ISSUE TITLE
[BUG] TLS error: failed to verify certificate: x509: certificate has expired or is not yet valid

### ISSUE THREAD

**Issue by DodoLeDev** [SpatiumPortae/portal#122]
**Describe the bug**
The TLS certificate of the main relay server seems to have expired

**To Reproduce**
1. Just try to send a file through the command line utility (`portal send ./somefile`)
2. Observe the error: `fetching the latest version from relay: Get "https://portal.spatiumportae.com/version": tls: failed to verify certificate: x509: certificate has expired or is not yet valid: current time 2023-08-09T18:13:30Z is after 2023-08-02T18:11:44Z`

**Expected behavior**
The communication with the server should work as always... until now.

**Screenshots**
What Firefox says about the webpage:
![image](https://github.com/SpatiumPortae/portal/assets/59477313/d31904dd-d0e0-4bdc-a8f0-6d6ac2144aa7)

**Platform / Portal version (please complete the following information):**
 - OS to which the bug applies: all. That's not a client problem
 - Portal Version: 1.2.3

**Additional context**
Did you know? Earth is the only planet not named after a God!

**Comment by ZinoKader** [comment]
Thank you for the bug report. It seems like the certficiation renewal script failed to run. All fixed now!
