### ISSUE TITLE
[bug] v1.2.3 shasum has changed

### ISSUE THREAD

**Issue by p-linnane** [SpatiumPortae/portal#123]
Hello 👋 . I'm a maintainer for the [Homebrew](https://brew.sh) project. We noticed that the shasum for v1.2.3 of portal has changed. We wanted to verify this is legitimate before updating it in our repository. Thanks!

Relates to https://github.com/Homebrew/homebrew-core/pull/139428.

**Comment by ZinoKader** [comment]
Hello there!

The change is legitimate and came from an initially faulty binary upload. Thank you for verifying.

**Comment by p-linnane** [comment]
Thank you!
