### ISSUE TITLE
Error compressing files.

### ISSUE THREAD

**Issue by Mattlau04** [SpatiumPortae/portal#25]
Hello, i'm trying to send a file using the command `portal --verbose send E01.mp4`, however it fails almost instantly with the only output being "Error compressing files."
What would be a good way to diagnose what's causing the issue? as even verbose mode doesn't say anything in particular

**Comment by ZinoKader** [comment]
That is strange, I think in that case errors during the compression stage do not propagate to stderr. If you are willing to share this file with us (if it's not private), I will have a look at it.
