### ISSUE TITLE
Switch default port to something other than `80`

### ISSUE THREAD

**Issue by mellonnen** [SpatiumPortae/portal#4]
When I try to run the rendezvous server locally I get this error,

![image](https://user-images.githubusercontent.com/66034456/149630470-3f144053-993d-4ae8-aa76-cdf59dda402d.png)

as port 80 is a privileged port and therefore a non-root process cannot use it.

Do not know if it is my setup or whatever but we should probably change it?

**Comment by ZinoKader** [comment]
Yes, the default should be some ephemeral TCP port, not 80 which is HTTP. 
How about 65432?

**Comment by mellonnen** [comment]
Also, it does not really make sense for the sender/receiver to have to provide IP and port individually. In the case, you want to send through a self-hosted rendezvous server you would have to provide both. We should probably accommodate both the `Sender` and `Receiver` stucts to accept an option for IP and port , and join the port and address cli flags into one flag
