### ISSUE TITLE
the relay_serve_port value is not taken into account from the config file

### ISSUE THREAD

**Issue by ludetie** [SpatiumPortae/portal#63]
Hello,

The relay_serve_port value is not taken into account from the config file (Windows 11) :
![image](https://user-images.githubusercontent.com/91374123/223754462-fb442eca-5c7c-4eef-997d-06661ea45eaa.png)
the behavior is the same on Ubuntu:
![image](https://user-images.githubusercontent.com/91374123/223759021-00a75387-d197-4da0-a211-ac0f9387616b.png)

Regards,

**Comment by ZinoKader** [comment]
Hi! The `relay_serve_port` regards the port at which the `portal serve` command would start the server.

Setting `relay_serve_port: 9999` would spare you from always specifying that port when running the relay server: `portal serve -p 9999`.

**Comment by ludetie** [comment]
OK ! Thank you !!

Regards,
