### ISSUE TITLE
[feature] scoop package for windows

### ISSUE THREAD

**Issue by omaru-ok** [SpatiumPortae/portal#87]
**Is your feature request related to a problem? Please describe.**
not a problem , but installtion will be really easy if it support [scoop](http://scoop.sh)

**Additional context**
also i want to zip files before seding . as sending very large folder with small files 
the speed go really down, 
such `croc send --zip`    have in croc already  READ here https://github.com/schollz/croc/issues/538

also a non -UI way like simple ouptut for headless server ?

**Comment by ZinoKader** [comment]
Hi! Thanks for the issue. 

To answer your first question about scoop, we will definitely add that soon, and perhaps Chocolatey as well.

Regarding your second question, Portal already archives and compressed files before sending, you do not need to do anything to make this happen. Simply list all the files and folders you want to send, and they will automatically be archived into a single `.tar` and compressed (in the background). While this is happening, you can share the password with the recipient, and the recipient can start the connection process as well. When the archiving and compression process is done, the transfer starts automatically.

**Comment by omaru-ok** [comment]
WOW, 
i will close the isseu as soon as scoop bucket is realeased

**Comment by omaru-ok** [comment]
![image](https://user-images.githubusercontent.com/108952834/227194809-dd37a98e-bf30-4717-9278-fbd620c7d23a.png)
as u can see output is not something good , 

i was asking for it already , how do i remove fancy ? UI for headless server which do not have any kind of true terminal output like modern terminal do

**Comment by mellonnen** [comment]
If you set the flag `--tui-style=raw` portal will run without the fancy terminal ui. You can also set the option `tui_style: raw` in your global config if you do not want to add the flag everytime you use portal.

**Comment by ZinoKader** [comment]
Closes with https://github.com/ScoopInstaller/Main/pull/4592

**Comment by ZinoKader** [comment]
Portal is now available in the main scoop bucket. Make sure to first run `scoop update`, then just run `scoop install portal`, and you're set!

Added in: 0516f0837c01eec12f39209fa3b960f03f8fd180

Closing this issue.

**Comment by omaru-ok** [comment]
goood 👍
